apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-ingress-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vishnuthatiparthi/K8s-ingress-project.git
    targetRevision: HEAD
    path: .     # Uses the root of your repository, change if all manifests are in a subfolder
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
